name: lidro
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - pip
  - pytest
  - gdal
  - laspy
  - numpy
  - scipy
  - rasterio
  - pyproj
  - pdal>=2.6
  - python-pdal>=3.2.1
    # --------- hydra configs --------- #
  - hydra-core==1.2.*
  - hydra-colorlog==1.2.*
