# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

io:
  input_filename: null
  input_dir: null
  output_dir: null
  srid: 2154
  extension: .tif
  raster_driver: GTiff
  pixel_size: 1
  no_data_value: -9999
  tile_size: 1000

raster:
  # size for dilatation
  dilatation_size: 3


vector:
  # Filter water's area (m²)
  min_water_area: 150
  # Parameters for buffer
  buffer_positive: 1
  buffer_negative: -1.5 # negative buffer should be bigger than positive buffer to prevent protruding over the banks
  # Tolerance from Douglas-Peucker
  tolerance: 1

filter:
  # Classes to be considered as "non-water"
  keep_classes: [0, 1, 2, 3, 4, 5, 6, 17, 64, 65, 66, 67] # All classes

SKELETON:
  FILE_PATH:
    MASK_INPUT_PATH:
    SKELETON_LINES_OUTPUT_PATH:  # only branches' skeleton (if empty, no file is created)
    GAP_LINES_OUTPUT_PATH:  # only new lines to close gaps (if empty, no file is created)
    GLOBAL_LINES_OUTPUT_PATH:  # lines from both the skeletons and the gap lines

  MAX_GAP_WIDTH: 200 # distance max in meter of any gap between 2 branches we will try to close with a line
  MAX_BRIDGES: 1 # number max of bridges that can be created between 2 branches
  GAP_WIDTH_CHECK_DB: 30 # for a gap at least this wide, we check with DB_UNI. Smaller than that, we assume a line automatically exists
  RATIO_GAP: 0.25 # when checking if a candidate line to close a gap intersects a bridge in BD UNI, that's the ratio ]0.1] of the line to consider.
                  # we only check part of the line, because when the line is really long it can intersect with bridges not corresponding to that line,
                  # so we make the line smaller

  DB_UNI:
    DB_NAME: bduni_france_consultation
    DB_HOST: bduni_consult.ign.fr
    DB_USER:
    DB_PASSWORD:
    DB_PORT: 5432

  BRANCH:
    VORONOI_MAX_LENGTH: 2 # max size of a voronoi line
    WATER_MIN_SIZE: 20 # min size of a skeleton line to be sure not to be removed 
    MAX_GAP_CANDIDATES: 3 # max number of candidates to close a gap between 2 branches

hydra:
  output_subdir: null
  run:
    dir: .