name: ci

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      # cf https://samuelsson.dev/access-private-submodules-in-github-actions/ for submodule fetching
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SUBMODULE_PULL_KEY }}
          submodules: 'recursive'

      # See https://github.com/marketplace/actions/setup-micromamba
      - name: Install conda env
        uses: mamba-org/setup-micromamba@v1.8.1
        with:
          environment-file: environment.yml
          environment-name: lidro  # activate the environment
          cache-environment: true
          cache-downloads: true
          generate-run-shell: true
      - name: Unit test
        shell: micromamba-shell {0}
        run: |
          cp .env_example .env
          python -m pytest -m "not returnfile and not bduni" -s --log-cli-level INFO
