name: ci

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          submodules: True
          token: ${{ secrets.GHCR_TOKEN }}
      # See https://github.com/marketplace/actions/setup-micromamba
      - name: Install conda env
        uses: mamba-org/setup-micromamba@v1.8.1
        with:
          environment-file: environment.yml
          environment-name: lidro  # activate the environment
          cache-environment: true
          cache-downloads: true
          generate-run-shell: true
      - name: Unit test
        shell: micromamba-shell {0}
        run: |
          cp .env_example .env
          sed -i "s/DB_UNI_USER='TO_BE_DEFINED'/DB_UNI_USER=${{ secrets.DB_UNI_USER }}/g" .env
          sed -i "s/DB_UNI_PASSWORD='TO_BE_DEFINED'/DB_UNI_PASSWORD=${{ secrets.DB_UNI_PASSWORD }}/g" .env
          python -m pytest -s --log-cli-level DEBUG
